###
POST http://localhost:8080/api/oauth/token
Content-Type: application/json

{
    "clientId" : "1",
    "secret" : "Ashan@123"
}

###
POST http://localhost:8080/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiU3ByaW5nLUJsb2ctQXBwIiwiaWF0IjoxNzcxNDI2ODY5LCJleHAiOjE3NzE0NTU2Njl9.M8Sr7KMlLbq-vATH3VBSCAr1KeHxN6sXcHu0ECgvjQs

{
  "name": "Joshua",
  "email": "ashanjoseph13@gmail.com",
  "password": "Josh@123"
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiU3ByaW5nLUJsb2ctQXBwIiwiaWF0IjoxNzcxNDI2ODY5LCJleHAiOjE3NzE0NTU2Njl9.M8Sr7KMlLbq-vATH3VBSCAr1KeHxN6sXcHu0ECgvjQs

{
  "email": "ashanjoseph13@gmail.com",
  "password": "Josh@123"
}

###
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "Importance of GO Lang",
  "description": "Explains about go lang and reason to learn it.",
  "userId" : 1
}

###
GET http://localhost:8080/api/posts/all-posts
Content-Type: application/json

###
GET http://localhost:8080/api/posts/show/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiU3ByaW5nLUJsb2ctQXBwIiwiaWF0IjoxNzcwMzAwMzQyLCJleHAiOjE3NzAzMjkxNDJ9.5Qn2Khf1VIL3JhyQls1XEi3qTXO5KnWwLhdidFdm9cY

###
POST http://localhost:8080/api/comments
Content-Type: application/json

{
  "userId": 1,
  "postId": 3,
  "comment" : "Post is clear and helpful"
}

###
POST http://localhost:8080/api/comments/change-visibility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiU3ByaW5nLUJsb2ctQXBwIiwiaWF0IjoxNzcwMzAwMzQyLCJleHAiOjE3NzAzMjkxNDJ9.5Qn2Khf1VIL3JhyQls1XEi3qTXO5KnWwLhdidFdm9cY

{
  "commentId": 6,
  "userId": 2,
  "commentStatus": "HIDE"

}

###
GET http://localhost:8080/api/comments/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiU3ByaW5nLUJsb2ctQXBwIiwiaWF0IjoxNzcwNzMyOTc1LCJleHAiOjE3NzA3NjE3NzV9.-B5_iM4FarYZO6hEDdL7NkrXixxXbN4YGZWWGVZEgQ0